import { expect } from "chai";
import { keccak256, type Address, type Hex } from "viem";
import { verifyTopology, type TopologyInput } from "../../../src/topology/verify";
import { type VaultPolicy } from "../../../src/config/policy";
const a = (n: number) => (`0x${n.toString(16).padStart(40, "0")}`) as Address;
const policy: VaultPolicy = { chainId: 31337, safe: a(1), passkey: a(2), burner: a(3), recovery: a(4), delay: a(5), periodSeconds: 86400, periodAnchor: 0n, cooldownSeconds: 3600, expirationSeconds: 86400, assets: [{ token: a(10), basePerTransaction: 10n, stepUpPerTransaction: 100n, baseDailyLimit: 100n, instantDailyLimit: 1000n, recipients: [a(20)] }] };
const code = "0x6001" as Hex; const hash = keccak256(code);
const values: Record<string, unknown> = { getOwners: [a(2), a(3), a(4)], getThreshold: 1n, getFallbackHandler: a(0), getGuard: a(6), getModuleGuard: a(6), getModules: [a(5)], isModuleEnabled: true, allowedRecipient: true, config: [a(1), a(2), a(3), a(4), a(5), 86400n, 0n], assetPolicy: [10n, 100n, 100n, 1000n], spendState: [0n, 0n, 0n], txCooldown: 3600n, txExpiration: 86400n, owner: a(1), avatar: a(1), target: a(1) };
function fixture(overrides: Record<string, unknown> = {}): TopologyInput { const data = { ...values, ...overrides }; return { chainId: 31337, policy, safe: a(1), guard: a(6), delay: a(5), expectedGuardCodeHash: hash, expectedDelayCodeHash: hash, client: { getBytecode: async () => code, readContract: async ({ functionName }: { functionName: string }) => data[functionName] } }; }
describe("verifyTopology", () => { it("returns a verified report only when every topology invariant is present", async () => { const report = await verifyTopology(fixture()); expect(report.ok).to.equal(true); expect(report.failures).to.deep.equal([]); }); it("fails closed on an unexpected owner", async () => { const report = await verifyTopology(fixture({ getOwners: [a(2), a(9), a(4)] })); expect(report.ok).to.equal(false); expect(report.failures.join(" ")).to.contain("owners"); }); it("fails closed on missing bytecode", async () => { const input = fixture(); input.client.getBytecode = async () => undefined; const report = await verifyTopology(input); expect(report.ok).to.equal(false); expect(report.failures.join(" ")).to.contain("bytecode"); }); });
