import { decodeEventLog, getAddress, parseAbi, type Address, type Hex } from "viem";
import { queueFingerprint } from "../queue/delay";
import type { ActivityAlert } from "./notifier";
import { MonitoringDecodeError, type MonitorLog } from "./guard-events";
export type { MonitorLog } from "./guard-events";

// Exact ABI evidenced by contracts/test/ZodiacDelayV1_1_1.sol. Unsupported lifecycle events are intentionally absent.
export const delayEventAbi=parseAbi(["event TransactionAdded(uint256 indexed queueNonce,bytes32 indexed txHash,address to,uint256 value,bytes data,uint8 operation)","event TxNonceSet(uint256 nonce)"]);
export type DelayMonitoringContext=Readonly<{chainId:number;safe:Address;delay:Address;confirmations:number;cooldownSeconds:bigint;expirationSeconds:bigint}>;
export type QueueItem=Readonly<{txHash:Hex;createdAt:bigint;to:Address;value:bigint;data:Hex;operation:number}>;
export type QueueBinding=Readonly<{readQueue:(queueNonce:bigint,blockNumber:bigint)=>Promise<QueueItem>;readNonce:(blockNumber:bigint)=>Promise<bigint>}>;
const same=(a:string,b:string)=>a.toLowerCase()===b.toLowerCase();
function check(log:MonitorLog,c:DelayMonitoringContext):void{if(!same(log.address,c.delay)||log.chainId!==c.chainId||log.removed)throw new MonitoringDecodeError("Delay event identity/reorg mismatch");if(!Number.isInteger(c.confirmations)||c.confirmations<1)throw new MonitoringDecodeError("invalid confirmation depth");}
export async function decodeDelayLog(log:MonitorLog,c:DelayMonitoringContext,latestBlock:bigint,observedAt:bigint,binding?:QueueBinding):Promise<ActivityAlert>{
 check(log,c);if(latestBlock-log.blockNumber+1n<BigInt(c.confirmations))throw new MonitoringDecodeError("unconfirmed Delay event");if(!binding||typeof binding.readQueue!=="function"||typeof binding.readNonce!=="function")throw new MonitoringDecodeError("verified Delay binding callback required");
 let d:{eventName:string;args:readonly unknown[]};try{d=decodeEventLog({abi:delayEventAbi,data:log.data,topics:[...log.topics] as [Hex,...Hex[]]}) as unknown as typeof d;}catch{throw new MonitoringDecodeError("malformed Delay event");}
 const v=Array.isArray(d.args)?d.args:Object.values(d.args);if(d.eventName==="TxNonceSet"){const nonce=v[0] as bigint;const current=await binding.readNonce(log.blockNumber);if(current<nonce)throw new MonitoringDecodeError("Delay nonce binding mismatch");return{kind:"delayed-cancelled",chainId:c.chainId,safe:c.safe,delay:c.delay,transactionHash:log.transactionHash,blockNumber:log.blockNumber,logIndex:log.logIndex,cancelledThrough:nonce};}
 if(d.eventName!=="TransactionAdded")throw new MonitoringDecodeError("unsupported Delay event");const [queueNonce,indexedHash,to,value,data,operation]=v as[bigint,Hex,Address,bigint,Hex,number];if(same(to,c.delay))throw new MonitoringDecodeError("Delay queue target binding mismatch");const recomputed=queueFingerprint({safe:c.safe,delay:c.delay,to:getAddress(to),value,data,operation:operation as 0|1,queueNonce});if(!same(indexedHash,recomputed))throw new MonitoringDecodeError("indexed Delay hash mismatch");
 return verifyDelayBinding({kind:"delayed-queued",chainId:c.chainId,safe:c.safe,delay:c.delay,transactionHash:log.transactionHash,blockNumber:log.blockNumber,logIndex:log.logIndex,queueNonce,queueFingerprint:recomputed,createdAt:observedAt,expiresAt:c.expirationSeconds===0n?undefined:observedAt+c.cooldownSeconds+c.expirationSeconds},binding,c);
}
export async function verifyDelayBinding(alert:ActivityAlert,binding:QueueBinding,c:DelayMonitoringContext):Promise<ActivityAlert>{if(alert.kind==="delayed-cancelled"){if(alert.cancelledThrough===undefined||await binding.readNonce(alert.blockNumber)<alert.cancelledThrough)throw new MonitoringDecodeError("Delay nonce binding mismatch");return alert;}if(alert.queueNonce===undefined||!alert.queueFingerprint||alert.createdAt===undefined)throw new MonitoringDecodeError("complete Delay binding required");const item=await binding.readQueue(alert.queueNonce,alert.blockNumber);const recomputed=queueFingerprint({safe:c.safe,delay:c.delay,to:item.to,value:item.value,data:item.data,operation:item.operation as 0|1,queueNonce:alert.queueNonce});if(!same(item.txHash,recomputed)||!same(item.txHash,alert.queueFingerprint)||item.createdAt!==alert.createdAt||same(item.to,c.delay)||!Number.isInteger(item.operation)||item.operation<0||item.operation>1)throw new MonitoringDecodeError("Delay queue binding mismatch");return alert;}
