import { decodeEventLog, encodeFunctionData, getAddress, parseAbi, type Address, type Hex } from "viem";
import type { ActivityAlert } from "./notifier";
export const guardEventAbi = parseAbi(["event TransferAuthorized(uint8 tier,address token,address recipient,uint256 amount,uint256 baseSpent,uint256 instantSpent,uint256 window)","event AuthorizationUsed(uint8 tier,address token,address recipient,uint256 amount,uint256 baseSpent,uint256 instantSpent,uint256 window)","event SpendingUpdated(address token,uint256 baseSpent,uint256 instantSpent,uint256 window)"]);
export type MonitoringIdentity = Readonly<{ chainId:number; safe:Address; guard:Address; delay:Address; confirmations:number }>;
export type MonitorLog = Readonly<{ address:Address; chainId?:number; blockNumber:bigint; blockHash:Hex; transactionHash:Hex; logIndex:number; topics:readonly Hex[]; data:Hex; removed?:boolean }>;
export type SafeTransaction = Readonly<{ safe:Address; to:Address; value:bigint; data:Hex; operation:number; nonce:bigint }>;
export type GuardBinding = Readonly<{ readSafeTransaction:(hash:Hex)=>Promise<SafeTransaction>; readSpendState:(token:Address)=>Promise<Readonly<{baseSpent:bigint;instantSpent:bigint;window:bigint}>>; expectedTransaction?:SafeTransaction }>;
export class MonitoringDecodeError extends Error {}
const same=(a:string,b:string)=>a.toLowerCase()===b.toLowerCase();
function check(log:MonitorLog,e:MonitoringIdentity):void { if(!same(log.address,e.guard)||log.chainId!==e.chainId||log.removed) throw new MonitoringDecodeError("guard event identity/reorg mismatch"); if(!Number.isInteger(e.confirmations)||e.confirmations<1) throw new MonitoringDecodeError("invalid confirmation depth"); }
export async function decodeGuardLog(log:MonitorLog,e:MonitoringIdentity,latestBlock:bigint,binding?:GuardBinding):Promise<ActivityAlert|undefined>{
 check(log,e); if(latestBlock-log.blockNumber+1n<BigInt(e.confirmations)) return undefined; if(!binding||typeof binding.readSafeTransaction!=="function"||typeof binding.readSpendState!=="function") throw new MonitoringDecodeError("verified guard binding callbacks required");
 let decoded:{eventName:string;args:readonly unknown[]}; try{decoded=decodeEventLog({abi:guardEventAbi,data:log.data,topics:[...log.topics] as [Hex,...Hex[]]}) as unknown as typeof decoded;}catch{throw new MonitoringDecodeError("malformed guard event");}
 if(decoded.eventName==="SpendingUpdated") return undefined; if(decoded.eventName!=="TransferAuthorized"&&decoded.eventName!=="AuthorizationUsed") return undefined;
 const [tier,token,recipient,amount,baseSpent,instantSpent,window]=(Array.isArray(decoded.args)?decoded.args:Object.values(decoded.args)) as [number,Address,Address,bigint,bigint,bigint,bigint]; if(Number(tier)!==1)return undefined;
 return verifyGuardBinding({kind:"step-up-executed",chainId:e.chainId,safe:e.safe,guard:e.guard,transactionHash:log.transactionHash,blockNumber:log.blockNumber,logIndex:log.logIndex,token:getAddress(token),recipient:getAddress(recipient),amount,baseSpent,instantSpent,window},binding,e);
}
export async function verifyGuardBinding(alert:ActivityAlert,binding:GuardBinding,e:MonitoringIdentity):Promise<ActivityAlert>{const tx=await binding.readSafeTransaction(alert.transactionHash); if(!same(tx.safe,e.safe)||!same(alert.safe,e.safe)||!same(alert.guard??"0x0",e.guard))throw new MonitoringDecodeError("guard binding identity mismatch"); if(binding.expectedTransaction&&(!same(tx.safe,binding.expectedTransaction.safe)||!same(tx.to,binding.expectedTransaction.to)||tx.value!==binding.expectedTransaction.value||tx.data.toLowerCase()!==binding.expectedTransaction.data.toLowerCase()||tx.operation!==binding.expectedTransaction.operation||tx.nonce!==binding.expectedTransaction.nonce))throw new MonitoringDecodeError("guard transaction binding mismatch"); const state=await binding.readSpendState(alert.token!); if(state.baseSpent!==alert.baseSpent||state.instantSpent!==alert.instantSpent||state.window!==alert.window)throw new MonitoringDecodeError("guard spend state binding mismatch"); if(!Number.isInteger(tx.operation)||tx.operation!==0||tx.nonce<0n)throw new MonitoringDecodeError("invalid Safe transaction binding"); const zero="0x0000000000000000000000000000000000000000";const expectedTo=alert.token&&same(alert.token,zero)?alert.recipient!:alert.token!;const expectedData=alert.token&&same(alert.token,zero)?"0x":encodeFunctionData({abi:parseAbi(["function transfer(address,uint256) returns (bool)"]),functionName:"transfer",args:[alert.recipient!,alert.amount!]});if(!same(tx.to,expectedTo)||tx.value!==(alert.token&&same(alert.token,zero)?alert.amount!:0n)||tx.data.toLowerCase()!==expectedData.toLowerCase())throw new MonitoringDecodeError("guard Safe transaction fields mismatch"); return alert;}
