import { isAddress, type Address, type Hex } from "viem";
export type ActivityKind="step-up-executed"|"delayed-queued"|"delayed-cancelled"|"delayed-executed"|"delayed-expired";
export type ActivityAlert=Readonly<{kind:ActivityKind;chainId:number;safe:Address;transactionHash:Hex;blockNumber:bigint;logIndex:number;guard?:Address;delay?:Address;token?:Address;recipient?:Address;amount?:bigint;baseSpent?:bigint;instantSpent?:bigint;window?:bigint;queueNonce?:bigint;queueFingerprint?:Hex;createdAt?:bigint;expiresAt?:bigint;to?:Address;value?:bigint;data?:Hex;operation?:number;cancelledThrough?:bigint}>;
export interface Notifier{notify(alert:ActivityAlert):Promise<void>}
const fields:Record<ActivityKind,readonly string[]>={"step-up-executed":["kind","chainId","safe","transactionHash","blockNumber","logIndex","guard","token","recipient","amount","baseSpent","instantSpent","window"],"delayed-queued":["kind","chainId","safe","transactionHash","blockNumber","logIndex","delay","queueNonce","queueFingerprint","createdAt","expiresAt","to","value","data","operation"],"delayed-cancelled":["kind","chainId","safe","transactionHash","blockNumber","logIndex","delay","cancelledThrough"],"delayed-executed":["kind","chainId","safe","transactionHash","blockNumber","logIndex","delay","queueNonce","queueFingerprint","createdAt","expiresAt","to","value","data","operation"],"delayed-expired":["kind","chainId","safe","transactionHash","blockNumber","logIndex","delay","queueNonce","queueFingerprint","createdAt","expiresAt","to","value","data","operation"]};
const required:Record<ActivityKind,readonly string[]>={"step-up-executed":["safe","transactionHash","blockNumber","logIndex","guard","token","recipient","amount","baseSpent","instantSpent","window"],"delayed-queued":["safe","transactionHash","blockNumber","logIndex","delay","queueNonce","queueFingerprint","createdAt"],"delayed-cancelled":["safe","transactionHash","blockNumber","logIndex","delay","cancelledThrough"],"delayed-executed":["safe","transactionHash","blockNumber","logIndex","delay","queueNonce","queueFingerprint","createdAt"],"delayed-expired":["safe","transactionHash","blockNumber","logIndex","delay","queueNonce","queueFingerprint","createdAt","expiresAt"]};
const addressFields=new Set(["safe","guard","delay","token","recipient","to"]);const hexFields=new Set(["transactionHash","queueFingerprint","data"]);const bigintFields=new Set(["blockNumber","amount","baseSpent","instantSpent","window","queueNonce","createdAt","expiresAt","value","cancelledThrough"]);const integerFields=new Set(["chainId","logIndex","operation"]);
export function publicAlert(alert:ActivityAlert):Record<string,unknown>{if(!alert||typeof alert!=="object")throw new Error("malformed alert");const allowed=fields[alert.kind];if(!allowed)throw new Error("unknown alert kind");for(const key of Object.keys(alert as object))if(!allowed.includes(key))throw new Error(`unknown or sensitive alert field: ${key}`);for(const key of required[alert.kind])if(!(key in alert)||alert[key as keyof ActivityAlert]===undefined)throw new Error(`required alert field missing: ${key}`);for(const key of allowed){if(!(key in alert)||alert[key as keyof ActivityAlert]===undefined)continue;const value=(alert as Record<string,unknown>)[key];if(addressFields.has(key)&&(typeof value!=="string"||!isAddress(value)))throw new Error(`invalid alert field type: ${key}`);if(hexFields.has(key)&&(typeof value!=="string"||!/^0x[0-9a-fA-F]*$/.test(value)||value.length%2!==0))throw new Error(`invalid alert field type: ${key}`);if(bigintFields.has(key)&&(typeof value!=="bigint"||value<0n))throw new Error(`invalid alert field type: ${key}`);if(integerFields.has(key)&&(!Number.isSafeInteger(value)||Number(value)<0))throw new Error(`invalid alert field type: ${key}`);}const out:Record<string,unknown>={};for(const key of allowed)if(key in alert)out[key]=(alert as Record<string,unknown>)[key];return out;}
const serialize=(a:ActivityAlert)=>JSON.stringify(publicAlert(a),(_,v)=>typeof v==="bigint"?v.toString():v);
export function createStdoutNotifier(write:(line:string)=>void=console.log):Notifier{return{notify:async a=>write(serialize(a))};}
export type WebhookFetch=(url:string,init?:{method?:string;headers?:Record<string,string>;body?:string})=>Promise<{ok:boolean;status:number}>;
export function createWebhookNotifier(url:string,fetcher:WebhookFetch=async(target,init)=>{const r=await fetch(target,init);return{ok:r.ok,status:r.status};}):Notifier{return{notify:async a=>{const r=await fetcher(url,{method:"POST",headers:{"content-type":"application/json"},body:serialize(a)});if(!r.ok)throw new Error(`notification webhook returned HTTP ${r.status}`);}};}
