/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LimitsRouteImport } from './routes/limits'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ReceiveRouteImport } from './routes/receive'
import { Route as SendRouteImport } from './routes/send'
import { Route as ActivityIndexRouteImport } from './routes/activity.index'
import { Route as ActivityIdRouteImport } from './routes/activity.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LimitsRoute = LimitsRouteImport.update({
  id: '/limits',
  path: '/limits',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceiveRoute = ReceiveRouteImport.update({
  id: '/receive',
  path: '/receive',
  getParentRoute: () => rootRouteImport,
} as any)
const SendRoute = SendRouteImport.update({
  id: '/send',
  path: '/send',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityIndexRoute = ActivityIndexRouteImport.update({
  id: '/activity/',
  path: '/activity/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityIdRoute = ActivityIdRouteImport.update({
  id: '/activity/$id',
  path: '/activity/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/limits': typeof LimitsRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/receive': typeof ReceiveRoute
  '/send': typeof SendRoute
  '/activity/$id': typeof ActivityIdRoute
  '/activity/': typeof ActivityIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/limits': typeof LimitsRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/receive': typeof ReceiveRoute
  '/send': typeof SendRoute
  '/activity/$id': typeof ActivityIdRoute
  '/activity': typeof ActivityIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/limits': typeof LimitsRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/receive': typeof ReceiveRoute
  '/send': typeof SendRoute
  '/activity/$id': typeof ActivityIdRoute
  '/activity/': typeof ActivityIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/limits'
    | '/onboarding'
    | '/profile'
    | '/receive'
    | '/send'
    | '/activity/$id'
    | '/activity/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/limits'
    | '/onboarding'
    | '/profile'
    | '/receive'
    | '/send'
    | '/activity/$id'
    | '/activity'
  id:
    | '__root__'
    | '/'
    | '/limits'
    | '/onboarding'
    | '/profile'
    | '/receive'
    | '/send'
    | '/activity/$id'
    | '/activity/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LimitsRoute: typeof LimitsRoute
  OnboardingRoute: typeof OnboardingRoute
  ProfileRoute: typeof ProfileRoute
  ReceiveRoute: typeof ReceiveRoute
  SendRoute: typeof SendRoute
  ActivityIdRoute: typeof ActivityIdRoute
  ActivityIndexRoute: typeof ActivityIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/limits': {
      id: '/limits'
      path: '/limits'
      fullPath: '/limits'
      preLoaderRoute: typeof LimitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receive': {
      id: '/receive'
      path: '/receive'
      fullPath: '/receive'
      preLoaderRoute: typeof ReceiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/send': {
      id: '/send'
      path: '/send'
      fullPath: '/send'
      preLoaderRoute: typeof SendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity/': {
      id: '/activity/'
      path: '/activity'
      fullPath: '/activity/'
      preLoaderRoute: typeof ActivityIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity/$id': {
      id: '/activity/$id'
      path: '/activity/$id'
      fullPath: '/activity/$id'
      preLoaderRoute: typeof ActivityIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LimitsRoute: LimitsRoute,
  OnboardingRoute: OnboardingRoute,
  ProfileRoute: ProfileRoute,
  ReceiveRoute: ReceiveRoute,
  SendRoute: SendRoute,
  ActivityIdRoute: ActivityIdRoute,
  ActivityIndexRoute: ActivityIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
