import { keccak256, parseAbi, type Address, type Hex } from "viem";
import { assertValidVaultPolicy, type VaultPolicy } from "../config/policy";
import { policyHash } from "./build";

export type TopologyReadClient = { getBytecode(args: { address: Address }): Promise<Hex | undefined>; readContract(args: { address: Address; abi: readonly unknown[]; functionName: string; args?: readonly unknown[] }): Promise<unknown> };
export type TopologyInput = Readonly<{ chainId: number; policy: VaultPolicy; safe: Address; guard: Address; delay: Address; safeSingleton: Address; expectedSafeVersion: string; expectedSafeProxyCodeHash: Hex; expectedGuardCodeHash: Hex; expectedDelayCodeHash: Hex; client: TopologyReadClient }>;
export type TopologyReport = Readonly<{ ok: boolean; failures: readonly string[]; checked: readonly string[] }>;

const ABI = parseAbi([
  "function masterCopy() view returns (address)", "function VERSION() view returns (string)", "function getOwners() view returns (address[])", "function getThreshold() view returns (uint256)", "function getFallbackHandler() view returns (address)", "function getGuard() view returns (address)", "function getModuleGuard() view returns (address)", "function getModules() view returns (address[])", "function isModuleEnabled(address) view returns (bool)",
  "function config() view returns (address,address,address,address,address,uint64,uint64)", "function assetPolicy(address) view returns (uint256,uint256,uint256,uint256)", "function spendState(address) view returns (uint256,uint256,uint256)", "function getPolicyRecipients(address) view returns (address[])", "function getConfiguredTokens() view returns (address[])", "function policyHash() view returns (bytes32)",
  "function owner() view returns (address)", "function avatar() view returns (address)", "function target() view returns (address)", "function txCooldown() view returns (uint256)", "function txExpiration() view returns (uint256)",
]);
const ZERO = "0x0000000000000000000000000000000000000000" as Address;
const same = (a: unknown, b: unknown) => typeof a === "string" && typeof b === "string" ? a.toLowerCase() === b.toLowerCase() : a === b;
const tuple = (value: unknown): readonly unknown[] | undefined => Array.isArray(value) ? value : undefined;

export async function verifyTopology(input: TopologyInput): Promise<TopologyReport> {
  const failures: string[] = []; const checked: string[] = [];
  const check = (name: string, condition: boolean) => { checked.push(name); if (!condition) failures.push(name); };
  try { assertValidVaultPolicy(input.policy); } catch (error) { failures.push("policy: " + (error instanceof Error ? error.message : "invalid")); return { ok: false, failures, checked }; }
  check("chain id", input.chainId === input.policy.chainId); check("safe address", same(input.safe, input.policy.safe)); check("delay address", same(input.delay, input.policy.delay)); check("guard address", input.guard.toLowerCase() !== ZERO);
  const code = async (label: string, address: Address, expected: Hex) => { try { const actual = await input.client.getBytecode({ address }); check(label + " bytecode", !!actual && actual !== "0x"); check(label + " code hash", !!actual && keccak256(actual).toLowerCase() === expected.toLowerCase()); } catch { check(label + " bytecode", false); check(label + " code hash", false); } };
  await code("Safe proxy", input.safe, input.expectedSafeProxyCodeHash); await code("guard", input.guard, input.expectedGuardCodeHash); await code("Delay", input.delay, input.expectedDelayCodeHash);
  const read = async (label: string, address: Address, functionName: string, args: readonly unknown[] = []): Promise<unknown> => { try { return await input.client.readContract({ address, abi: ABI, functionName, args }); } catch { failures.push(label + " read"); return undefined; } };
  const masterCopy = await read("Safe singleton", input.safe, "masterCopy"); check("Safe proxy singleton", same(masterCopy, input.safeSingleton)); check("Safe version", (await read("Safe version", input.safe, "VERSION")) === input.expectedSafeVersion);
  const owners = tuple(await read("owners", input.safe, "getOwners")); check("owners", !!owners && owners.length === 3 && owners.every((x, i) => same(x, [input.policy.passkey, input.policy.burner, input.policy.recovery][i])));
  check("threshold", (await read("threshold", input.safe, "getThreshold")) === 1n); check("fallback handler", same(await read("fallback handler", input.safe, "getFallbackHandler"), ZERO)); check("transaction guard", same(await read("transaction guard", input.safe, "getGuard"), input.guard)); check("module guard", same(await read("module guard", input.safe, "getModuleGuard"), input.guard));
  const modules = tuple(await read("modules", input.safe, "getModules")); check("only Delay module", !!modules && modules.length === 1 && same(modules[0], input.delay)); check("Delay enabled", (await read("Delay enabled", input.safe, "isModuleEnabled", [input.delay])) === true);
  const config = tuple(await read("guard config", input.guard, "config")); check("guard config", !!config && same(config[0], input.safe) && same(config[1], input.policy.passkey) && same(config[2], input.policy.burner) && same(config[3], input.policy.recovery) && same(config[4], input.delay) && config[5] === 86400n && config[6] === input.policy.periodAnchor); check("policy hash", (await read("policy hash", input.guard, "policyHash")) === policyHash(input.policy));
  const configuredTokens = tuple(await read("configured assets", input.guard, "getConfiguredTokens")); check("configured assets", !!configuredTokens && configuredTokens.length === input.policy.assets.length && configuredTokens.every((x, i) => same(x, input.policy.assets[i]?.token)));
  for (const asset of input.policy.assets) { const configured = tuple(await read("asset policy " + asset.token, input.guard, "assetPolicy", [asset.token])); check("asset policy " + asset.token, !!configured && configured[0] === asset.basePerTransaction && configured[1] === asset.stepUpPerTransaction && configured[2] === asset.baseDailyLimit && configured[3] === asset.instantDailyLimit); const recipients = tuple(await read("recipients " + asset.token, input.guard, "getPolicyRecipients", [asset.token])); check("recipients " + asset.token, !!recipients && recipients.length === asset.recipients.length && recipients.every((x, i) => same(x, asset.recipients[i]))); const state = tuple(await read("counter " + asset.token, input.guard, "spendState", [asset.token])); check("counter " + asset.token, !!state && state.length === 3 && typeof state[0] === "bigint" && (state[1] as bigint) <= asset.baseDailyLimit && (state[2] as bigint) <= asset.instantDailyLimit); }
  check("Delay owner", same(await read("Delay owner", input.delay, "owner"), input.safe)); check("Delay avatar", same(await read("Delay avatar", input.delay, "avatar"), input.safe)); check("Delay target", same(await read("Delay target", input.delay, "target"), input.safe)); check("Delay cooldown", (await read("Delay cooldown", input.delay, "txCooldown")) === BigInt(input.policy.cooldownSeconds)); check("Delay expiration", (await read("Delay expiration", input.delay, "txExpiration")) === BigInt(input.policy.expirationSeconds)); check("Delay upstream Safe", (await read("Delay upstream Safe", input.delay, "isModuleEnabled", [input.safe])) === true);
  return { ok: failures.length === 0, failures, checked };
}
